### ISSUE TITLE
Why repository isn't suggested as a singleton?

### ISSUE THREAD

**Issue by sgserg** [google-developer-training/android-kotlin-fundamentals-starter-apps#1]
In the Repository lesson (9.1) a repo is set up step by step, hiding DB-cached network resources.

How come it is **not** suggested to ever create just one of those?

Neither does it protect itself against concurrent multiple cache refreshes (by multiple repo instances). It's a blunt `Dao.insertAll` at the end of a refresh.

**Comment by hatchermarie2** [comment]
Dao.insertall/python
