### ISSUE TITLE
Base URL in MarsApiService.kt

### ISSUE THREAD

**Issue by oguzhandurmaz** [google-developer-training/android-kotlin-fundamentals-starter-apps#18]
In MarsRealEstate-Starter project BASE_URL is wrong. It must be "https://android-kotlin-fun-mars-server.appspot.com"

**Comment by hatchermarie2** [comment]
[Bootstack_datasheet.pdf](https://github.com/google-developer-training/android-kotlin-fundamentals-starter-apps/files/4173857/Bootstack_datasheet.pdf)

**Comment by jtavva** [comment]
Fixed in https://github.com/google-developer-training/android-kotlin-fundamentals-starter-apps/commit/f08ece813105ef7b076468d96550aff8c6dd3ee5#diff-28bb9c7778b764e998b94f0a92ff381b
