### ISSUE TITLE
GDGFinder app has `drawer_view.xml` with conflict symbols

### ISSUE THREAD

**Issue by shadowsheep1** [google-developer-training/android-kotlin-fundamentals-starter-apps#2]
![image](https://user-images.githubusercontent.com/16268789/62633100-e81a0200-b933-11e9-9eff-5da6b797c9c8.png)

**Comment by edgarjc** [comment]
This is what the code should look like.

> <?xml version="1.0" encoding="utf-8"?>

<menu xmlns:app="http://schemas.android.com/apk/res-auto" xmlns:android="http://schemas.android.com/apk/res/android">

    <item android:title="@string/gdg_search" android:id="@+id/gdg_search"
    />
    <item android:title="@string/gdg_apply" android:id="@+id/gdg_apply"/>
</menu>

>

**Comment by edgarjc** [comment]
Everything above line 5 needs to be deleted from the file. Here's what the code should look like:
```
<?xml version="1.0" encoding="utf-8"?>
<menu xmlns:app="http://schemas.android.com/apk/res-auto" xmlns:android="http://schemas.android.com/apk/res/android">

    <item android:title="@string/gdg_search" android:id="@+id/gdg_search"
    />
    <item android:title="@string/gdg_apply" android:id="@+id/gdg_apply"/>
</menu>
```

**Comment by GeneAndGoogle** [comment]
Fixed.
