### ISSUE TITLE
Missed Migration to androidx for Navigation Component.

### ISSUE THREAD

**Issue by nyxee** [google-developer-training/android-kotlin-fundamentals-starter-apps#23]
For [GDGFinder-Starter](https://github.com/google-developer-training/android-kotlin-fundamentals-starter-apps/tree/master/GDGFinder-Starter)

**GIVEN IN THE CODE:**
```{gradle}
//app  build.gradle file:
version_navigation = "1.0.0"
classpath "android.arch.navigation:navigation-safe-args-gradle-plugin:$version_navigation"


//module  build.gradle file:
implementation "android.arch.navigation:navigation-fragment-ktx:$version_navigation"
implementation "android.arch.navigation:navigation-ui-ktx:$version_navigation"
```
**CORRECTION:**
```{gradle}
//app  build.gradle
version_navigation = "2.3.0"
classpath "androidx.navigation:navigation-safe-args-gradle-plugin:$$version_navigation"

//module  build.gradle file:
implementation "androidx.navigation:navigation-fragment-ktx:$version_navigation" 
implementation "androidx.navigation:navigation-ui-ktx:$version_navigation"
```
The given code compiled correctly but led to an error on one of my devices (**Samsung Galaxy TAB S6** _SM-T865_, _Android 10 - API 29_ ) while it worked on other devices.

ERROR:
[navAndXError.txt](https://github.com/google-developer-training/android-kotlin-fundamentals-starter-apps/files/4908281/navAndXError.txt)

**Comment by jtavva** [comment]
This is fixed now. Thank you for reporting.
