### ISSUE TITLE
ViewModelProviders

### ISSUE THREAD

**Issue by 2000Vlad** [google-developer-training/android-kotlin-fundamentals-starter-apps#24]
As stated here : https://developer.android.com/reference/androidx/lifecycle/ViewModelProviders
The `ViewModelProviders` class is deprecated.
Instead of `viewModel = ViewModelProviders.of(this).get(GameViewModel::class.java)` you should use
`val provider = ViewModelProvider(this, ViewModelProvider.NewInstanceFactory()`
`viewModel = provider.get(GameViewModel::class.java`

**Comment by jtavva** [comment]
Fixed
