### ISSUE TITLE
Gradle refuse to build

### ISSUE THREAD

**Issue by mahmoud-abdallah863** [google-developer-training/android-kotlin-fundamentals-starter-apps#35]
Error:
Could not execute build using Gradle distribution 'https://services.gradle.org/distributions/gradle-6.1.1-all.zip'.

I tired older and newer versions, but no luck

**Comment by jtavva** [comment]
Thank you for reaching out to us.
Which code sample are codelab are you facing this issue?

**Comment by mahmoud-abdallah863** [comment]
All the versions of TrackMySleepQuality apps.

The same gradle version works on others apps except these.

**Comment by jtavva** [comment]
The recommended Android studio version stable version, please try Android Studio 4.0.1, if you still face issue please let us know. Also, please provide the error log.   
Thank you for reaching out to us.
