### ISSUE TITLE
deprecated method ViewModelProviders.of(this) in Mars Real Estate- Starter

### ISSUE THREAD

**Issue by Unicorn-Sol** [google-developer-training/android-kotlin-fundamentals-starter-apps#39]
Mars Real Estate- Starter has deprecated method to initialize view model

**Comment by TheCodingArcher** [comment]
Duplicate of #24

**Comment by jtavva** [comment]
This issue should be fixed now. 
Please check the pull request: https://github.com/google-developer-training/android-kotlin-fundamentals-starter-apps/pull/28

Thank you for reaching out to us.
