### ISSUE TITLE
Handle orientation ourselves in “AndroidTrivia-Starter”?

### ISSUE THREAD

**Issue by lopespm** [google-developer-training/android-kotlin-fundamentals-starter-apps#5]
In "AndroidTrivia-Starter", configuration changes are signaled as [being handled by the MainActivity](https://github.com/google-developer-training/android-kotlin-fundamentals-starter-apps/blob/master/AndroidTrivia-Starter/app/src/main/AndroidManifest.xml#L30). Is there an underlying reason for this?

If not, I can submit a patch to remove this attribute.

**Comment by joseantoniocampillo** [comment]
android.arch.navigation:navigation-..  dependencie keep a bug wich fix whith it.
But best solution is update libraries for navigation to:
androidx.navigation:navigation-...

**Comment by jtavva** [comment]
It should be fixed now. Please check it.
