### ISSUE TITLE
Guess The Word starter BUG

### ISSUE THREAD

**Issue by SayantanBanerjee16** [google-developer-training/android-kotlin-fundamentals-starter-apps#56]
Whenever I clone and open the project, I get the following bug:-
`TtileFragment.kt`
`findNavController().navigate(TitleFragmentDirections.actionTitleToGame())`

TitleFragmentDirections is not being recognized.

Refer to the screenshot for proof:-

![Screenshot (184)](https://user-images.githubusercontent.com/43978143/104161757-61ffc600-5419-11eb-9ca6-7eea3b613c63.png)

How to fix it?

**Comment by masumo** [comment]
I also faced similar situation. I thought it was a bug. But then, I just tried to run the app and it worked well. 
After the gradle build finished, somehow the error disappear.

**Comment by SayantanBanerjee16** [comment]
Thanks for the explanation.
