### ISSUE TITLE
No repository pattern starter code to download

### ISSUE THREAD

**Issue by intliziyo** [google-developer-training/android-kotlin-fundamentals-starter-apps#89]

**Comment by intliziyo** [comment]
I'm doing the Kotlin course and there's supposed to be a main branch, in order to download zip or clone project, but nothing

https://github.com/google-developer-training/android-kotlin-fundamentals-starter-apps/tree/master/RepositoryPattern-Starter

**Comment by Hitendra27** [comment]
Facing the same issue brother!!!

**Comment by manu2315** [comment]
I'm facing the same issue, I can't clone the repo

**Comment by xellrzr** [comment]
unable to download starter code :(

**Comment by spamshot** [comment]
Hello all.
You'll need to download the full fundamentals zip first then go to sleep tracker.
[Full Zip](https://github.com/google-developer-training/android-kotlin-fundamentals-starter-apps)

**Comment by Hitendra27** [comment]
Thanks @spamshot it works by downloading the full fundamentals zip.

**Comment by ChampikDev** [comment]
RepositoryPattern-Starter cannot start project. Could you please make a normal link to download the project, like it was in previous codelabs?

**Comment by xascar** [comment]
> RepositoryPattern-Starter cannot start project. Could you please make a normal link to download the project, like it was in previous codelabs?

You need to select the <b>RepositoryPattern-Starter</b> folder and then open, it will not work if you are selecting the <b>app</b> folder neither the root folder

<img width="799" alt="image" src="https://user-images.githubusercontent.com/8994634/202053165-a0422f8c-af96-464e-8599-a8a59528ca06.png">

**Comment by kemicky** [comment]
Yeap , I just solve this  now too, 
 - Download the entire file 
 - Click on the starter code folder you need,
 -  then open is android studio

**Comment by Sachin-Timilsina** [comment]
I think I found the solution we need to go to the former path [android-kotlin-fundamentals-starter-apps](https://github.com/google-developer-training/android-kotlin-fundamentals-starter-apps) 
1. Download that zip file in the path.
2. Extract those files in the computer.
3. Find the DevsByte-Strater and open it in android studio.

**Comment by spamshot** [comment]
Thank you all but the issue has been resolved.
